/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "An unhandled error has occurred.": "发生了一个未处理的错误。",
    "for suggestions, guides, and community": "为建议，指南和社区",
    "Import Save": "导入存档",
    "Join the": "加入",
    "Loading Data...": "加载数据…",
    "Normal": "正常",
    "Hardcore": "硬核",
    "Ultimate": "极限",
    "Ultimate)": "极限)",
    "Hardcore)": "硬核)",
    "Normal)": "正常)",
    "Normal mode is the normal way to play the game. It's highly recommended you start out playing in this game mode.": "普通模式是玩游戏的正常方式。 强烈建议您以这种游戏模式开始玩。",
    "Note:For best results, Quepland needs to be played in a separate window. Most browsers will pause the game after a few minutes in a background tab.": "注意：为获得最佳效果，需要在单独的窗口中玩 奎普大陆。 大多数浏览器会在几分钟后在后台选项卡中暂停游戏。",
    "Reload": "重新加载",
    "Please consider supporting development on": "请考虑支持开发者",
    "Quepland 2 is a semi-idle adventure game set in the world of Quepland. It is heavily inspired by the developer's childhood addiction to Runescape.": "奎普大陆 2 是一款以 奎普大陆 世界为背景的半放置冒险游戏。 它的灵感来自开发者童年时对 Runescape 的沉迷。",
    "See Updates": "查看更新",
    "Select Game Mode": "选择游戏模式",
    "Version": "版本",
    "Welcome to Quepland": "欢迎来到 奎普大陆",
    "All": "全部",
    "Craft": "制作",
    "Bank": "银行",
    "Deposit All": "全部存款",
    "Equip": "装备",
    "Git游戏": "吉特游戏",
    "Hide": "隐藏",
    "Inv": "库存",
    "Last Save": "上次保存",
    "Loot": "战利品",
    "Mount Queple": "奎普尔山",
    "Open Experience Tracker": "打开体验跟踪器",
    "Quantity": "数量",
    "Quantity:": "数量：",
    "Quepland 2 (": "奎普大陆 2 (",
    "Quests": "任务",
    "Search": "搜索",
    "Show Tabs": "显示标签",
    "Skills": "技能",
    "Space": "空间",
    "Team": "队伍",
    "Textile Arts": "纺织艺术",
    "Textile arts include the manipulation of fibers into cloths. There are a variety of materials that can be manipulated into some form of clothing in the world of Quepland.": "纺织艺术包括将纤维加工成布料。在克普兰的世界里，有各种各样的材料可以被加工成某种形式的服装。",
    "The ability to engrave, cut, and polish gemstones, and to apply them to weapons and armor.": "雕刻、切割和抛光宝石并将其应用于武器和盔甲的能力。",
    "There is a small stream and a forest of white pine trees. A large poplar tree has been chopped and laid across the path. You'll need to chop through it to continue on the path.": "有一条小溪和一片白松树林。一棵大白杨树被砍倒并横放在小路上。你需要穿过它才能继续走这条路。",
    "Thumb": "拇指",
    "Tin Arrowtips": "锡箭尖",
    "Tin Axe": "锡斧",
    "Tin Bar": "锡吧",
    "Tin Hammer": "锡锤",
    "Tin Knife": "锡刀",
    "Tin Ore": "锡矿",
    "Tin Sword": "锡剑",
    "Token": "令牌",
    "Tokoloshe": "托科洛舍",
    "Total Level": "总水平",
    "Toto": "托托",
    "Tough Wood Shavings": "坚韧的刨花",
    "Tumbled Amberite": "坠落的琥珀",
    "Tumbled Amethyst": "碎紫水晶",
    "Tumbled Aquamarine": "海蓝宝石",
    "Tumbled Chrysoberyl": "翻滚的金绿玉",
    "Tumbled Diamond": "坠落的钻石",
    "Tumbled Emerald": "坠落的祖母绿",
    "Tumbled Garnet": "翻滚的石榴石",
    "Tumbled Lizardite": "翻滚的蜥蜴",
    "Tumbled Opal": "碎蛋白石",
    "Tumbled Purpurite": "翻滚的紫水晶",
    "Tumbled Ruby": "红宝石",
    "Tumbled Sapphire": "坠落的蓝宝石",
    "Tumbled Topaz": "翻滚黄玉",
    "Tuna": "金枪鱼",
    "Tuna Roll": "金枪鱼卷",
    "Turkey": "火鸡",
    "Turkey Jerky": "火鸡干",
    "Turn Rate Tracker On": "打开速率跟踪器",
    "Tuto": "图托",
    "Two Bandits": "两个土匪",
    "Ultimate Pickaxe": "终极镐",
    "Ultimate Test Weapon": "终极测试武器",
    "Ultimate Test Weapon Two, Electric Boogaloo": "终极测试武器二，电动布加卢",
    "Umami Zombie": "鲜味僵尸",
    "Vasilly": "瓦西里",
    "Visitang": "访问",
    "Waist": "腰部",
    "Wari": "瓦里",
    "What do I do?": "我该怎么办？",
    "Where is my bank?": "我的银行在哪里？",
    "White Cotton Cape": "白棉披风",
    "White Pine Arrow": "白松箭",
    "White Pine Arrow Shafts": "白松箭杆",
    "White Pine Bow": "白松弓",
    "White Pine Bow(Unstrung": "白松弓（未弦",
    "White Pine Logs": "白松原木",
    "White Pine Shield": "白松盾",
    "White Silk Cape": "白丝披风",
    "White Wool Cape": "白色羊毛披风",
    "Wild Boar": "野猪",
    "Wild Boar Boots": "野猪靴",
    "Wild Boar Gloves": "野猪手套",
    "Wild Boar Hat": "野猪帽",
    "Wild Boar Pants": "野猪裤",
    "Wild Boar Shirt": "野猪衬衫",
    "Wild Kushtaka": "野生库什塔卡",
    "Withdraw All Stone Axe": "撤回所有石斧",
    "Wizz": "威兹",
    "Wonny": "万尼",
    "Wood Shavings": "刨花",
    "Woodcutting": "木刻",
    "Woodcutting is the first skill you learned in the world of Quepland, and it has a variety of uses. Some paths on your journey will only be accesible with a high enough woodcutting level.": "木刻是你在克普兰世界学到的第一项技能，它有多种用途。您旅途中的某些路径只有在木刻水平足够高的情况下才能进入。",
    "Woodworking": "木工",
    "Woodworking is the act of cutting away parts of logs to make them more useful. You can train it by chiselling away at logs, or by finding one of the totems around Quepland.": "木工是切割部分原木以使其更有用的行为。您可以通过凿凿原木或在奎普兰附近找到其中一个图腾来训练它。",
    "Wool Thread": "毛线",
    "Woolly Mammoth": "猛犸象",
    "Writhing Skeleton": "扭动的骷髅",
    "x": "X",
    "X": "X",
    "Yellowtail": "黄尾鱼",
    "Yellowtail Roll": "黄尾鱼卷",
    "You chop some white pine logs.": "你砍了一些白松原木。",
    "You chop some white pine logs.(2": "你砍了一些白松原木。（2",
    "You chop some white pine logs.(3": "你砍了一些白松原木。（3",
    "You don't have a task right now. Speak to a guild member to get one.": "你现在没有任务。与公会成员交谈以获得一个。",
    "You don't have any tools for Woodcutting": "你没有任何木刻工具",
    "You don't have the materials to craft anything.": "你没有制作任何东西的材料。",
    "You haven't started this quest yet. Go to Mound's Boats at the Uragota docks to begin.": "你还没有开始这个任务。前往浦田码头的 Mound's Boats 开始。",
    "You haven't started this quest yet. Talk Camel Carl at the Desert's Mouth to begin.": "你还没有开始这个任务。开始在沙漠之口与骆驼卡尔交谈。",
    "You haven't started this quest yet. Talk to the mayor in Teppas to begin.": "你还没有开始这个任务。与 Teppas 的市长交谈开始。",
    "You haven't started this quest yet. Talk Tuto in Quepland Fields to begin.": "你还没有开始这个任务。在 奎普大陆 田野 与 Tuto 交谈开始。",
    "You haven't started this quest yet. You'll need to complete Mound is Missing before starting this quest on the pirate ship in Uragota Town.": "你还没有开始这个任务。在浦田镇的海盗船上开始此任务之前，您需要完成: 土墩不见了。",
    "You haven't started this quest yet. You'll need to find Queple's grave to begin.": "你还没有开始这个任务。您需要找到 Queple 的坟墓才能开始。",
    "You need 2 Woodcutting\nYou don't have any tools for Woodcutting": "您需要 2 个木刻\n您没有任何木刻工具",
    "You swing your axe at a tree.": "你在树上挥动你的斧头。",
    "You've started the quest Oriole Ornithology.": "你已经开始了金莺鸟类学任务。",
    "Zinc Arrowtips": "锌箭头",
    "Zinc Axe": "锌斧",
    "Zinc Bar": "锌棒",
    "Zinc Hammer": "锌锤",
    "Zinc Knife": "锌刀",
    "Zinc Sword": "锌剑",
    "Zombisword": "僵尸剑",
    "Smithing consists of two parts: the creation of bars from ores, and the creation of items from those bars. Ores mined or purchased can be transported to a smithy where they can be melted down into bars, or hammered into weapons, armor, and tools. There are a variety of metals in the world of Quepland, each with their own special properties.": "锻造由两部分组成：用矿石制造锭，以及用这些锭制造物品。 开采或购买的矿石可以被运送到铁匠铺，在那里它们可以被熔化成锭，或者被锤成武器、盔甲和工具。 奎普兰世界中的金属种类繁多，每一种都有自己的特殊属性。",
    "Strength is the power with which you use weapons. All weapons use strength when calculating your damage dealt but only swords, axes, and hammers grant strength experience when you battle with them. Every level also increases your inventory capacity by 1, and every 10th level by 2.": "力量是你使用武器的力量。 所有武器在计算你造成的伤害时都会使用力量，但只有剑、斧头和锤子在你与它们战斗时才会提供力量经验。 每升一级，你的库存容量增加 1，每 10 级增加 2。",
    "Swordsmanship is your ability to wield swords. Swords are slower than knives, but quite a bit stronger. They have well-rounded stats that deal decent damage at reasonable speeds.": "剑术是你挥舞剑的能力。 剑比刀慢，但要强得多。 他们拥有全面的统计数据，可以在合理的速度下造成可观的伤害。",
    "Salmon Roll": "三文鱼卷",
    "Salty Zombie": "咸僵尸",
    "Sam": "山姆",
    "Sand Golem": "沙傀儡",
    "Sand Ray": "沙雷",
    "Sand Worm": "沙虫",
    "Sandcrawler": "沙行者",
    "Sandthrasher": "磨沙者",
    "Sapphire Necklace": "蓝宝石项链",
    "Sardine": "沙丁鱼",
    "Sardine Roll": "沙丁鱼卷",
    "Sashcom": "Sashcom",
    "Saury": "秋刀鱼",
    "Saury Roll": "秋刀鱼卷",
    "Sawabe Swiper": "泽部刷子",
    "Scallop": "扇贝",
    "Scallop Roll": "扇贝卷",
    "Scoph": "斯科普",
    "Select an item to craft.": "选择要制作的物品。",
    "Serpopard": "蛇豹",
    "Shad": "鲱鱼",
    "Shad Roll": "鲱鱼卷",
    "Shifnam": "希夫南",
    "Show Messages": "显示消息",
    "Shrimp": "虾",
    "Shrimp Roll": "虾卷",
    "Shunai": "周内",
    "Silk Thread": "丝线",
    "Silver Bar": "银条",
    "Silver Necklace": "银项链",
    "Silver Ore": "银矿石",
    "Sleeper Shark": "沉睡鲨",
    "Sleeper Shark Roll": "卧铺鲨鱼卷",
    "Slime": "粘液",
    "Small Caiman": "小凯门鳄",
    "Small Fishing Rod": "小钓竿",
    "Small Kappa": "小河童",
    "Small Net": "小网",
    "Smashy": "粉碎",
    "Smithing": "锻造",
    "Smwojo": "斯姆沃乔",
    "Snakewood Arrow": "蛇木箭",
    "Snakewood Arrow Shafts": "蛇木箭杆",
    "Snakewood Bow": "蛇木弓",
    "Snakewood Bow(Unstrung": "蛇木弓（未弦",
    "Snakewood Logs": "蛇木原木",
    "Snakewood Shield": "蛇木盾",
    "Sodo": "索多",
    "Sour Zombie": "酸僵尸",
    "Spicy Zombie": "辣僵尸",
    "Spindle": "主轴",
    "Spine Shooter": "脊椎射手",
    "Squid": "乌贼",
    "Squid Roll": "鱿鱼卷",
    "Stealthy Root Dweller": "隐身的根居民",
    "Steel Arrowtips": "钢箭尖",
    "Steel Axe": "钢斧",
    "Steel Bar": "金属棒",
    "Steel Hammer": "钢锤",
    "Steel Knife": "钢刀",
    "Steel Pickaxe": "钢镐",
    "Steel Sword": "钢剑",
    "Steelflame Axe": "钢焰斧",
    "Stellifowl": "星禽",
    "Stone Axe": "石斧",
    "Stone Pickaxe": "石镐",
    "Stop Gathering": "停止聚会",
    "Stormling": "暴风女",
    "Stormsight Shield": "风暴之盾",
    "Stormwood Logs": "暴风木原木",
    "Stormwood Shield": "暴风林之盾",
    "Strength": "力量",
    "Strong Buloke Arrow": "强力布洛克箭",
    "Strong Lignum Vitae Arrow": "强大的木质素箭",
    "Strong Root Dweller": "强根居民",
    "Strong Snakewood Arrow": "强蛇木箭",
    "Strongtium Arrowtips": "锶 箭尖",
    "Strongtium Axe": "强力斧",
    "Strongtium Bar": "强力棒",
    "Strongtium Hammer": "大力神锤",
    "Strongtium Knife": "锶刀",
    "Strongtium Ore": "锶矿",
    "Strongtium Pickaxe": "锶镐",
    "Strongtium Sword": "大力神剑",
    "Sugar Maple Bow": "糖枫弓",
    "Sugar Maple Bow(Unstrung": "糖枫弓（未弦",
    "Sugar Maple Logs": "糖枫原木",
    "Sulmenkan Trident": "苏门坎三叉戟",
    "Sunfish": "翻车鱼",
    "Sunfish Roll": "翻车鱼卷",
    "Sweet Dough": "甜面团",
    "Sweet Zombie": "甜蜜的僵尸",
    "Swings": "秋千",
    "Swordfish": "旗鱼",
    "Swordfish Roll": "剑鱼卷",
    "Swordsmanship": "剑术",
    "Tanto": "这么多",
    "Mining can be trained anywhere you can find ores in the ground. Above ground, ore veins must be found before you mine them. Each ore you acquire deplete the vein further, requiring more time to get the next ore. This does not apply to ore veins you find beneath the surface of Quepland.": "可以在任何可以在地下找到矿石的地方训练采矿。 在地面上，必须先找到矿脉，然后才能开采它们。 你获得的每一种矿石都会进一步消耗矿脉，需要更多的时间来获得下一种矿石。 这不适用于您在奎普兰地表下发现的矿脉。",
    "Mesquite Arrow": "豆科植物箭",
    "Mesquite Arrow Shafts": "豆科植物箭轴",
    "Mesquite Bow": "豆科植物弓",
    "Mesquite Bow(Unstrung": "豆科植物弓（未弦",
    "Mesquite Logs": "豆科灌木原木",
    "Mesquite Shield": "豆科植物盾牌",
    "Milk Dough": "牛奶面团",
    "Mining": "矿业",
    "Minnow Net": "米诺网",
    "Minnow Roll": "米诺卷",
    "Minnows": "小鱼",
    "Moose": "驼鹿",
    "Moose Boots": "驼鹿靴",
    "Moose Gloves": "驼鹿手套",
    "Moose Hat": "驼鹿帽",
    "Moose Hat(Antlered": "驼鹿帽(鹿角",
    "Moose Jerky": "驼鹿肉干",
    "Moose Pants": "驼鹿裤",
    "Moose Shirt": "驼鹿衬衫",
    "Mound Is Missing": "土墩不见了",
    "Munny": "蒙尼",
    "Neck": "脖子",
    "Needle": "针",
    "Nickel Arrowtips": "镍箭头",
    "Nickel Axe": "镍斧",
    "Nickel Bar": "镍棒",
    "Nickel Hammer": "镍锤",
    "Nickel Knife": "镍刀",
    "Nickel Sword": "镍剑",
    "No Soliciting Sign": "禁止征集标志",
    "Oak Arrow": "橡树箭",
    "Oak Arrow Shafts": "橡木箭杆",
    "Oak Bow": "橡木弓",
    "Oak Bow(Unstrung": "橡木弓（未弦",
    "Oak Logs": "橡木原木",
    "Oak Shield": "橡木盾",
    "Oar Fish": "桨鱼",
    "Octopus Roll": "章鱼卷",
    "One Blade Billy": "一剑比利",
    "Oni": "鬼",
    "Opal Necklace": "蛋白石项链",
    "Oriole Ornithology": "黄鹂鸟类学",
    "Over on the left sidebar, towards the top! Just click there and you should see a Stone Axe that you got as a sign-up bonus.": "在左侧边栏上，朝顶部！只需单击那里，您就会看到作为注册奖励获得的石斧。",
    "Pentlandite": "五角闪石",
    "Pheasant": "野鸡",
    "Pheasant Jerky": "野鸡肉干",
    "Pigeon": "鸽子",
    "Pigeon Jerky": "鸽子肉干",
    "Plastinium Ore": "铂矿",
    "Platinum Arrowtips": "铂金箭头",
    "Platinum Axe": "白金斧",
    "Platinum Bar": "铂金条",
    "Platinum Hammer": "白金锤",
    "Platinum Knife": "铂金刀",
    "Platinum Necklace": "铂金项链",
    "Platinum Ore": "铂矿",
    "Platinum Sword": "白金剑",
    "Polar Bear": "北极熊",
    "Poplar Arrow": "杨箭",
    "Poplar Arrow Shafts": "杨树箭杆",
    "Poplar Bow": "白杨弓",
    "Poplar Bow(Unstrung": "白杨弓（未弦",
    "Poplar Logs": "杨木原木",
    "Poplar Shield": "杨树盾",
    "Puffer Fish": "河豚鱼",
    "Puffer Fish Roll": "河豚鱼卷",
    "Purpurite Necklace": "紫水晶项链",
    "QQ群号": "QQ群号",
    "Quepland Fields": "奎普兰田野",
    "Queple's Sword": "奎普尔之剑",
    "Queplinium Ore": "奎匹林 矿石",
    "R Hand": "右手",
    "Rabbit": "兔子",
    "Rabbit Boots": "兔靴",
    "Rabbit Gloves": "兔子手套",
    "Rabbit Hat": "兔子帽",
    "Rabbit Jerky": "兔肉干",
    "Rabbit Pants": "兔裤",
    "Rabbit Shirt": "兔衬衫",
    "Ravenous Root Dweller": "贪婪的根居民",
    "Razzmatazz": "狂欢节",
    "River Clam": "河蚌",
    "Rocker": "摇杆",
    "Roo": "罗",
    "Rooster": "公鸡",
    "Root Bow": "根弓",
    "Root Dweller": "根居民",
    "Ruby Necklace": "红宝石项链",
    "Rye Dough": "黑麦面团",
    "Rye Dough (Unleavened": "黑麦面团（无酵",
    "Rye Flour": "黑麦面粉",
    "Sahotite Arrowtips": "萨霍特 箭尖",
    "Sahotite Axe": "萨霍特斧",
    "Sahotite Hammer": "萨霍特之锤",
    "Sahotite Knife": "萨霍蒂刀",
    "Sahotite Ore": "萨霍特矿石",
    "Sahotite Sword": "萨霍蒂剑",
    "Salami": "萨拉米",
    "Salmon": "三文鱼",
    "Leatherworking is working with leather. To acquire leather you need to find a tannery and tan your pelts you acquire from hunting animals. There is a mysterious traveller in the Rising Hills who can guide you closer to what you need.": "皮革加工正在使用皮革。 要获得皮革，您需要找到一家制革厂，并将您从狩猎动物中获得的毛皮晒黑。 升起的山丘 有一位神秘的旅行者，他可以引导您更接近您需要的东西。",
    "Ion the Island Bandit King": "离子岛强盗王",
    "Iron Arrowtips": "铁箭尖",
    "Iron Axe": "铁斧",
    "Iron Bar": "铁棒",
    "Iron Hammer": "铁锤",
    "Iron Knife": "铁刀",
    "Iron Knuckles": "铁指关节",
    "Iron Ore": "铁矿",
    "Iron Pickaxe": "铁镐",
    "Iron Sword": "铁剑",
    "Ironwood Arrow": "铁木箭",
    "Ironwood Arrow Shafts": "铁木箭杆",
    "Ironwood Bow": "铁木弓",
    "Ironwood Bow(Unstrung": "铁木弓（未弦",
    "Ironwood Logs": "铁木原木",
    "Ironwood Shield": "铁木盾",
    "Iseroite Ring": "伊塞罗石戒指",
    "It's an axe made of stone.": "这是一把石头做的斧头。",
    "Italian Christmas Tree": "意大利圣诞树",
    "Jikumena Beast": "吉库摩那兽",
    "Just click to chop some White Pine trees and you'll gain experience in Woodcutting. You can see your experience by clicking Skills at the top of the right sidebar.": "只需点击砍一些白松树，你就会获得伐木经验。您可以通过单击右侧边栏顶部的技能来查看您的体验。",
    "Kaiken": "开垦",
    "Kappa": "河童",
    "Knifesmanship": "刀法",
    "Knifesmanship is your ability to use all kinds of knives as weapons. Knives are the fastest weapons you can wield, but also the weakest. They tend to be good for killing weak things quickly.": "刀法是您将各种刀具用作武器的能力。刀是你可以使用的最快的武器，但也是最弱的。它们往往适合快速杀死弱小的东西。",
    "Kozuka": "小冢",
    "Kraewtin": "克劳廷",
    "Kurisutay": "库里苏泰",
    "L Hand": "左手",
    "Lake Hand": "湖手",
    "Lapidary": "宝石",
    "Large Caiman": "大凯门鳄",
    "Large Fishing Rod": "大钓竿",
    "Large Net": "大网",
    "Large Sand Worm": "大沙虫",
    "Lasah": "拉萨",
    "Lead Arrowtips": "铅箭头提示",
    "Lead Axe": "铅斧",
    "Lead Bar": "铅条",
    "Lead Knife": "铅刀",
    "Lead Sword": "铅剑",
    "Leatherworking": "制皮",
    "Leave me alone! I know what I'm doing.": "请别打扰我！我知道我在做什么。",
    "Legs": "腿",
    "Lesser Lead Hammer": "小铅锤",
    "Level": "等级",
    "Lignum Vitae Arrow": "木本生命之箭",
    "Lignum Vitae Arrow Shafts": "Lignum Vitae 箭杆",
    "Lignum Vitae Bow": "木香弓",
    "Lignum Vitae Bow(Unstrung": "Lignum Vitae 弓（无弦",
    "Lignum Vitae Logs": "木质素原木",
    "Lignum Vitae Shield": "Lignum Vitae 盾",
    "Lilytrap": "百合",
    "Lion's Mane Jellyfish": "狮鬃水母",
    "Living Cactus": "活仙人掌",
    "Living Rock": "活石",
    "Lizardite Necklace": "蜥蜴石项链",
    "Lizardite Ring": "蜥蜴戒指",
    "Mack": "麦克",
    "Magic Iron Sword": "魔铁剑",
    "Magic Net": "魔网",
    "Magician": "魔术师",
    "Mahogany Arrow": "桃花心木箭",
    "Mahogany Arrow Shafts": "桃花心木箭杆",
    "Mahogany Bow": "桃花心木弓",
    "Mahogany Bow(Unstrung": "桃花心木弓（未弦",
    "Mahogany Logs": "红木原木",
    "Mahogany Shield": "桃花心木盾",
    "Main": "主要的",
    "Mammoth Boots": "猛犸象靴",
    "Mammoth Gloves": "猛犸象手套",
    "Mammoth Hat": "猛犸帽",
    "Mammoth Jerky": "猛犸肉干",
    "Mammoth Pants": "猛犸象裤",
    "Mammoth Shirt": "猛犸衬衫",
    "Manananggal": "马南加尔",
    "Manfish": "人鱼",
    "Manta Ray": "蝠鲼",
    "Manta Ray Roll": "蝠鲼卷",
    "Mapinguari": "马平瓜里",
    "Maple Arrow": "枫叶箭",
    "Maple Arrow Shafts": "枫木箭杆",
    "Maple Shield": "枫叶盾",
    "Masakar": "马萨卡",
    "Mayor's Assistant": "市长助理",
    "Medium Fishing Rod": "中型钓竿",
    "Medium Net": "中网",
    "Mercurial Beast": "水银野兽",
    "Mercurial Giant": "水银巨人",
    "Mercurial Knight": "水银骑士",
    "Mercurial Malformation": "汞畸形",
    "Mercurial Man": "水星人",
    "Mercurial Sword": "水银剑",
    "Mercurial Warrior": "水银战士",
    "Mercurice Axe": "水银斧",
    "Mercurice Hammer": "水银锤",
    "Mercurice Knife": "水银刀",
    "Mercurice Sword": "水银剑",
    "Mes": "梅斯",
    "HP is short for hitpoints, and it is trained by taking damage during combat. When your HP reaches 0, it means you are no longer in a condition to continue fighting, and you must flee your current battle. When you flee, some opponents will not pursue you, but others may require a bribe to let you go.": "HP 是生命值的缩写，它是通过在战斗中受到伤害来训练的。 当您的HP为0时，表示您不再处于继续战斗的状态，您必须逃离当前的战斗。 当你逃跑时，一些对手不会追你，但其他人可能需要贿赂才能放你走。",
    "Hunting is a skill that can only be trained on hunting trips. Taking a hunting trip can take a long time, but it also can offer a bounty of rewards. Legends tell of a number of secret hunting locations throughout Quepland. Try to find them!": "狩猎是一种只能在狩猎旅行中训练的技能。 狩猎旅行可能需要很长时间，但它也可以提供丰厚的回报。 传说讲述了整个奎普兰的许多秘密狩猎地点。 试着找到他们！",
    "Fishing is the act of capturing creatures that live in the water. There are a variety of fish around Quepland, and the most lucrative and interesting ones will require a good bit of fishing knowledge to capture.": "钓鱼是捕捉生活在水中的生物的行为。 奎普大陆 附近有各种各样的鱼，最赚钱和最有趣的鱼需要掌握大量的钓鱼知识才能捕获。",
    "Enraged Attendant": "愤怒的侍从",
    "Eqalussuaq": "小牛",
    "Eqalussuaq Roll": "白马卷",
    "Eun": "恩",
    "Exp:0\nFor Level:100\nRemaining:100": "经验:0\n对于级别:100\n剩余:100",
    "Explore the world and maybe you'll find some others who would join you on your adventure. They might not do it for free, though.": "探索世界，也许您会发现其他人会加入您的冒险之旅。不过，他们可能不会免费这样做。",
    "Extremely Tough Wood Shavings": "极其坚硬的刨花",
    "Ezai": "以载",
    "Feet": "脚",
    "Fets": "Fets",
    "Fighter Frog": "战斗机蛙",
    "Fish Knife": "鱼刀",
    "Fishing": "钓鱼",
    "Fishman": "鱼人",
    "Flounder": "比目鱼",
    "Flounder Roll": "比目鱼卷",
    "Flour": "面粉",
    "Frost Bat": "冰霜蝙蝠",
    "Frost Fighter": "冰霜战士",
    "Futo": "布托",
    "Fuzzy": "模糊",
    "Galena": "方铅矿",
    "Garnet Necklace": "石榴石项链",
    "Gashadokuro Head": "合影六郎头",
    "Gashadokuro Left Hand": "合影六郎左手",
    "Gashadokuro R Hand": "合影六郎 R 手",
    "Gashadokuro Spine": "合影六郎脊椎",
    "Gem Mine Gem": "宝石矿宝石",
    "Giant Bat": "巨型蝙蝠",
    "Giant Carp": "巨鲤",
    "Giant Clam": "巨蛤",
    "Giant Clam Roll": "巨蛤卷",
    "Giant Octopus": "巨型章鱼",
    "Giant Polar Bear": "巨型北极熊",
    "Glad you asked! To get past that log in front of you, you'll need to learn how to chop down trees. Go to your bank and withdraw your axe!": "很高兴你问了！为了绕过你面前的那根木头，你需要学习如何砍伐树木。去你的银行，取出你的斧头！",
    "Gold Bar": "金条",
    "Gold Necklace": "金项链",
    "Gold Ore": "金矿",
    "Golden Arrowtips": "金色箭头",
    "Golden Axe": "金斧",
    "Golden Hammer": "金锤",
    "Golden Knife": "金刀",
    "Golden Sword": "金剑",
    "Graingilt Archer": "格兰吉尔特弓箭手",
    "Graingilt Guard": "格兰吉尔特卫队",
    "Grand Theft Camel": "侠盗猎车手骆驼",
    "Great Arrow": "大箭",
    "Great Arrow Shaft Pack": "大箭轴包",
    "Great Arrow Shafts": "大箭杆",
    "Great Tree Bow": "大树弓",
    "Great Tree Bow(Unstrung": "大树弓（未弦",
    "Great Tree Logs": "大树原木",
    "Great Wood Shield": "大木盾",
    "Greater Lead Hammer": "大铅锤",
    "Grizzly Bear": "大灰熊",
    "Grizzly Bear Boots": "灰熊靴子",
    "Grizzly Bear Gloves": "灰熊手套",
    "Grizzly Bear Hat": "灰熊帽子",
    "Grizzly Bear Pants": "灰熊裤",
    "Grizzly Bear Shirt": "灰熊衬衫",
    "Ground Grupper": "地面组队",
    "Halibut": "比目鱼",
    "Halibut Roll": "比目鱼卷",
    "Hammermanship": "锤法",
    "Hammermanship is your ability to swing hammers properly in combat. Hammers are the slowest weapon type you can wield, but also the strongest.": "锤法是您在战斗中正确挥动锤子的能力。锤子是你可以使用的最慢的武器类型，但也是最强的。",
    "Hands": "手",
    "Head": "头",
    "Headless Birch Arrows": "无头桦木箭",
    "Headless Buloke Arrows": "无头野箭",
    "Headless Great Arrows": "无头大箭",
    "Headless Ice Arrows": "无头冰箭",
    "Headless Ironwood Arrows": "无头铁木箭",
    "Headless Lignum Vitae Arrows": "无头生命之树箭",
    "Headless Mahogany Arrows": "无头桃花心木箭",
    "Headless Maple Arrows": "无头枫叶箭",
    "Headless Mesquite Arrows": "无头豆科植物箭",
    "Headless Oak Arrows": "无头橡木箭",
    "Headless Poplar Arrows": "无头杨箭",
    "Headless Snakewood Arrows": "无头蛇木箭",
    "Headless White Pine Arrows": "无头白松箭",
    "Heavy Ironwood Arrow": "重铁木箭",
    "Heavy Mesquite Arrow": "重型豆科植物箭",
    "Hello": "你好",
    "Hi! You look like you're not from around here. Wanna learn more about the world you're in?": "你好！你看起来不是这里的人。想更多地了解你所处的世界吗？",
    "Hide Tabs": "隐藏标签",
    "HP": "生命值",
    "Hunting": "打猎",
    "Hydral Wolf": "多头狼",
    "I have my axe, now what?": "我有我的斧头，现在呢？",
    "Ice Arrow": "冰箭",
    "Ice Arrow Shafts": "冰箭轴",
    "Ice Logs": "冰原木",
    "Ice Spider": "冰蜘蛛",
    "Ice Wood Shield": "冰木盾",
    "Icefish": "冰鱼",
    "Icefish Roll": "冰鱼卷",
    "Imaynimayn": "伊迈尼迈因",
    "Culinary Arts involves taking raw materials and converting them into digestible materials through physical and chemical changes. Ultimately this boils down to making sushi rolls and curing meats into jerky.": "烹饪艺术涉及获取原材料并通过物理和化学变化将其转化为可消化的材料。 最终这归结为制作寿司卷和将肉类腌制成肉干。",
    "Bitter Zombie": "苦僵尸",
    "Black Bear": "黑色的熊",
    "Black Bear Boots": "黑熊靴",
    "Black Bear Gloves": "黑熊手套",
    "Black Bear Hat": "黑熊帽",
    "Black Bear Pants": "黑色熊裤",
    "Black Bear Shirt": "黑色小熊衬衫",
    "Boar Jerky": "野猪肉干",
    "Bone Blade": "骨刃",
    "Brass Arrowtips": "黄铜箭头",
    "Brass Axe": "黄铜斧",
    "Brass Hammer": "黄铜锤",
    "Brass Knife": "黄铜刀",
    "Brass Sword": "黄铜剑",
    "Bronze Arrowtips": "青铜箭头",
    "Bronze Axe": "青铜斧",
    "Bronze Hammer": "青铜锤",
    "Bronze Knife": "青铜刀",
    "Bronze Pickaxe": "青铜镐",
    "Bronze Sword": "青铜剑",
    "Buck": "巴克",
    "Buloke Arrow": "布洛克箭",
    "Buloke Arrow Shafts": "布洛克箭杆",
    "Buloke Bow": "布洛克弓",
    "Buloke Bow(Unstrung": "Buloke 弓（未弦",
    "Buloke Logs": "Buloke 原木",
    "Buloke Shield": "布洛克盾",
    "Butterfish": "鲳鱼",
    "Butterfish Roll": "鲳鱼卷",
    "Cactus Club": "仙人掌俱乐部",
    "Caiman": "凯门鳄",
    "Caiman Belt": "凯门鳄腰带",
    "Caiman Boots": "凯门鳄靴",
    "Caiman Gloves": "凯门鳄手套",
    "Caiman Hat": "凯门鳄帽",
    "Caiman Jerky": "凯门鳄肉干",
    "Caiman Pants": "凯门鳄裤",
    "Caiman Shirt": "凯门鳄衬衫",
    "Calamine": "炉甘石",
    "Cape": "岬",
    "Carp": "鲤鱼",
    "Carp Roll": "鲤鱼卷",
    "Case of the Dead Pirate": "死海贼案",
    "Chelonic Fragments": "甲虫碎片",
    "Chelonic Powder": "海藻粉",
    "Chelonite": "海藻石",
    "Chenoo": "陈努",
    "Chest": "胸部",
    "Chicken": "鸡",
    "Chicken Jerky": "鸡肉干",
    "Chill Chicken": "冷鸡",
    "Chill Egg": "冷藏鸡蛋",
    "Chop White Pine": "剁碎白松",
    "Chrysoberyl Necklace": "金绿玉项链",
    "Chrysoberyl Ring": "金绿宝石戒指",
    "Chrysopoeian Crisis": "金星危机",
    "Cinnabar": "辰砂",
    "Clear away tree": "清除树",
    "Coal": "煤炭",
    "Colossal Squid": "巨型鱿鱼",
    "Confirm": "确认",
    "Copper Arrowtips": "铜箭头",
    "Copper Axe": "铜斧",
    "Copper Bar": "铜棒",
    "Copper Hammer": "铜锤",
    "Copper Knife": "铜刀",
    "Copper Ore": "铜矿",
    "Copper Sword": "铜剑",
    "Cotton Thread": "棉线",
    "Crab": "螃蟹",
    "Crab Roll": "蟹卷",
    "Culinary Arts": "烹饪艺术",
    "Current Points": "当前积分",
    "Daiges": "代格斯",
    "Danbura": "丹布拉",
    "Dancing Skeleton": "跳舞骷髅",
    "Deba": "德巴",
    "Deer": "鹿",
    "Deer Boots": "鹿靴",
    "Deer Gloves": "鹿手套",
    "Deer Hat": "鹿帽",
    "Deer Jerky": "鹿肉干",
    "Deer Pants": "鹿裤",
    "Deer Shirt": "鹿衬衫",
    "Deftness": "灵巧",
    "Deftness is the speed at which you use weapons. Knives, swords, and axes all grant deftness experience when you battle with them. Deftness will slightly increase your attack speed.": "敏捷度是你使用武器的速度。刀、剑和斧头在与它们战斗时都会提供敏捷经验。敏捷会略微提高你的攻击速度。",
    "Delete Tab": "删除标签",
    "Diamond Necklace": "钻石项链",
    "Dos": "DOS",
    "Dough": "面团",
    "Dough (Unleavened": "面团（无酵",
    "Dreian": "德里安",
    "Durum Dough": "硬粒面团",
    "Durum Dough (Unleavened": "杜兰姆面团（无酵",
    "Durum Flour": "硬粒小麦粉",
    "Earth Golem": "土傀儡",
    "Ebisian Fishing Rod": "Ebisian 钓鱼竿",
    "Emerald Necklace": "翡翠项链",
    "Emerald Ring": "祖母绿戒指",
    "Alchemy is the most difficult skill in the world of Quepland, but mastering it can be quite lucrative. Around Mount Queple reside four Great Halls, built before the current settlers arrived here. Using the special properties of each hall, an alchemist can combine the base metals with one of the four base elements to transmute their metal into a more valuable one. As you learn more alchemical recipes, they will appear in this menu for future reference.": "炼金术是奎普大陆世界中最难的技能，但掌握它会非常有利可图。 Queple 山周围有四个大厅，这些大厅是在当前的定居者到达这里之前建造的。 利用每个大厅的特殊属性，炼金术士可以将贱金属与四种基本元素之一结合，将它们的金属转化为更有价值的金属。 随着您了解更多炼金术配方，它们将出现在此菜单中以供将来参考。",
    "Artisan covers the general knowledge required to produce skill craftworks. As you improve at artisan you can take on more and larger tasks, as well as unlock access to new areas and items. Speak to a guild member at any craft guild to get started.": "工匠涵盖了制作技能工艺品所需的一般知识。 随着您在工匠方面的进步，您可以承担更多更大的任务，并解锁对新区域和物品的访问权限。 与任何工艺公会的公会成员交谈即可开始。",
    "Abalone": "鲍鱼",
    "Abalone Roll": "鲍鱼卷",
    "Add Tab": "添加标签",
    "Advanced Dough": "高级面团",
    "Akhlut": "阿赫鲁特",
    "Akku": "阿库",
    "Alchemy": "炼金术",
    "Aluminum Arrowtips": "铝制箭头",
    "Aluminum Axe": "铝斧",
    "Aluminum Bar": "铝棒",
    "Aluminum Hammer": "铝锤",
    "Aluminum Knife": "铝刀",
    "Aluminum Sword": "铝剑",
    "Amberite Necklace": "琥珀项链",
    "Amethyst Necklace": "紫水晶项链",
    "Amphisbaena": "两栖类",
    "Ancient Pickaxe": "古代镐",
    "Angler Squirrel": "钓鱼松鼠",
    "Angry Crab": "愤怒的螃蟹",
    "Angry Crab Roll": "愤怒的螃蟹卷",
    "Angry Hunter": "愤怒的猎人",
    "Aquamarine Necklace": "海蓝宝石项链",
    "Arao": "荒尾",
    "Archery": "射箭",
    "Archery is your ability to wield a bow and shoot arrows. It also helps ensure a player going hunting doesn't return empty handed after a trip.": "射箭是您使用弓箭射箭的能力。它还有助于确保去打猎的玩家在旅行后不会空手而归。",
    "Artisan": "工匠",
    "Axemanship": "斧术",
    "Axemanship is your ability to use axes in combat. They are slower than swords or knives, but faster than hammers. Some enemies are exceptionally weak to axes.": "斧术是你在战斗中使用斧头的能力。它们比剑或刀慢，但比锤子快。有些敌人对斧头特别弱。",
    "Back": "后退",
    "Balsa Logs": "轻木原木",
    "Bandit": "土匪",
    "Bandit King": "土匪王",
    "Bandit Lord": "土匪领主",
    "Bandit's Boots": "强盗之靴",
    "Bandit's Knife": "强盗的刀",
    "Bandit's Sword": "强盗之剑",
    "Baobhan Cape": "包班披风",
    "Baobhan Sith": "鲍班西斯",
    "Baobhan Thread": "猴面包树线",
    "Bat": "蝙蝠",
    "Bauxite": "铝土矿",
    "Bean": "豆角，扁豆",
    "Bear Jerky": "熊肉干",
    "Beastiary": "兽人",
    "Behemoth Scorpion": "巨蝎",
    "Big Bandit": "大盗",
    "Big Moose": "大驼鹿",
    "Big Tuna": "大金枪鱼",
    "Big Tuna Roll": "大金枪鱼卷",
    "Birch Arrow": "桦木箭",
    "Birch Arrow Shafts": "桦木箭杆",
    "Birch Bow": "桦木弓",
    "Birch Bow(Unstrung": "桦木弓（无弦",
    "Birch Logs": "桦木原木",
    "Birch Shield": "桦木盾",
    "Bison": "野牛",
    "Bison Boots": "野牛靴",
    "Bison Gloves": "野牛手套",
    "Bison Hat": "野牛帽",
    "Bison Jerky": "野牛肉干",
    "Bison Pants": "野牛裤",
    "Bison Shirt": "野牛衬衫",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "Patreon": "Patreon",
    "Discord": "Discord",
    "Credits": "鸣谢",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    '': '',
    '': '',

}


//需处理的前缀
var cnPrefix = {
    "(-": "(-",
    "(+": "(+",
    "(": "(",
    "-": "-",
    "+": "+",
    " ": " ",
    ": ": "： ",
    "\n": "",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": "",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\n                    ": "\n                    ",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Begin New Game": "开始新游戏",
    "Load Game (": "加载游戏 (",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀
var cnPostfix = {
    ":": "：",
    "：": "：",
    ": ": "： ",
    "： ": "： ",
    "/s)": "/s)",
    "/s": "/s",
    ")": ")",
    "%": "%",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": " ",
    "\n": "",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "Last Save": "上次保存",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+)e(\d+)$/,
    /^([\d\.]+)$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
var cnRegReplace = new Map([
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
    [/^([\d\.]+) Leatherworking$/, '$1 制皮'],
    [/^([\d\.]+) Archery$/, '$1 射箭'],
    [/^([\d\.]+) Woodcutting$/, '$1 木刻'],
    [/^([\d\.]+) Woodworking$/, '$1 木工'],
    [/^([\d\.]+) Culinary Arts$/, '$1 艺术'],
    [/^([\d\.]+) Fishing$/, '$1 钓鱼'],
    [/^([\d\.]+) Knifesmanship$/, '$1 刀法'],
    [/^([\d\.]+) Mining$/, '$1 采矿'],
    [/^([\d\.]+) Smithing$/, '$1 锻造'],
    [/^([\d\.]+) Swordsmanship$/, '$1 剑法'],
    [/^([\d\.]+) Lapidary$/, '$1 宝石'],
    [/^([\d\.]+) Axemanship$/, '$1 斧术'],
    [/^([\d\.]+) Hammermanship$/, '$1 锤法'],
    [/^([\d\.]+) Hunting$/, '$1 狩猎'],
	[/^([\d\.,]+)\/sec$/, '$1\/秒'],
	[/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Req: (.+) \/ (.+) elves$/, '成本：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);